<?php

use Drupal\Core\Field\WidgetInterface;
use Drupal\Core\Field\FieldDefinitionInterface;
use Drupal\Core\Form\FormStateInterface;
use Drupal\inline_entity_form_template\InlineEntityFormTemplate;

/**
 * Implements hook_field_widget_third_party_settings_form().
 *
 * @param \Drupal\Core\Field\WidgetInterface $plugin
 * @param \Drupal\Core\Field\FieldDefinitionInterface $field_definition
 * @param $form_mode
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 *
 * @return array
 */
function inline_entity_form_template_field_widget_third_party_settings_form(WidgetInterface $plugin, FieldDefinitionInterface $field_definition, $form_mode, $form, FormStateInterface $form_state) {
  return InlineEntityFormTemplate::widgetSettingsForm($plugin, $field_definition, $form_mode, $form, $form_state);
}

/**
 * Implements hook_field_widget_settings_summary_alter().
 *
 * @param $summary
 * @param $context
 */
function inline_entity_form_template_field_widget_settings_summary_alter(&$summary, $context) {
  InlineEntityFormTemplate::alterWidgetSettingsSummary($summary, $context);
}

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 *
 * @param $element
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $context
 *
 * @see hook_field_widget_form_alter()
 */
function inline_entity_form_template_field_widget_inline_entity_form_complex_form_alter(&$element, FormStateInterface $form_state, $context) {
  InlineEntityFormTemplate::alterWidgetForm($element, $form_state, $context);
}
